
###########################
###  Setup those first  ###
###########################
$furball = ~/.config/hypr
$hl = $furball/hyprland

$terminal = kitty
$fileManager = thunar
$menu = hyprlauncher
$web-browser = zen-browser
$code-editor = code


device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

#################
###  Include  ###
#################
source = $hl/monitors.conf
source = $hl/autostart.conf
source = $hl/general.conf
source = $hl/input.conf
source = $hl/windowrules.conf
source = $hl/keybindings.conf
source = $hl/decoration.conf
source = $hl/env.conf









#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general


# https://wiki.hypr.land/Configuring/Variables/#decoration


# https://wiki.hypr.land/Configuring/Variables/#animations


# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }

# See https://wiki.hypr.land/Configu23ring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}




# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more



###################
### KEYBINDINGS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules


