general {
    immediate_render = true
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /path/to/your/wallpaper.png   # Change this!
    blur_passes = 2
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    position = 0, -20
    halign = center
    valign = center
}