#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us, ua
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false  # Optional: inverted scrolling
        tap-to-click = true
        clickfinger_behavior = false # Enables 2-finger tap for right-click, 3-finger for middle
    }
}
