################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=eDP-1,1920x1080,auto,1

# preload = ~/Files/Pictures/Wallpapers/wallpaper1.jpg
# wallpaper=,/home/ahd/Files/Pictures/Wallpapers/wallpaper1.jpg

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    background_color = 0x9999
}